# Generated by Django 2.2.5 on 2021-10-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbDept',
            fields=[
                ('dept_seq', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dept_nm', models.CharField(max_length=255)),
                ('upper_dept_seq', models.CharField(max_length=255)),
                ('all_dept_seq', models.CharField(max_length=255)),
                ('sort', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_dept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TCode',
            fields=[
                ('code', models.CharField(db_column='CODE', max_length=50, primary_key=True, serialize=False)),
                ('group_code', models.CharField(db_column='GROUP_CODE', max_length=50)),
                ('code_nm', models.CharField(blank=True, db_column='CODE_NM', max_length=100, null=True)),
                ('code_val', models.CharField(blank=True, db_column='CODE_VAL', max_length=30, null=True)),
                ('code_etc', models.CharField(blank=True, db_column='CODE_ETC', max_length=30, null=True)),
                ('regist_dt', models.DateTimeField(blank=True, db_column='REGIST_DT', null=True)),
            ],
            options={
                'db_table': 't_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TDetailIndicator',
            fields=[
                ('detail_indicator_seq', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='CODE', max_length=50, null=True)),
                ('gubun', models.CharField(blank=True, db_column='GUBUN', max_length=50, null=True)),
                ('year', models.CharField(blank=True, db_column='YEAR', max_length=10, null=True)),
                ('detail_index', models.CharField(blank=True, db_column='DETAIL_INDEX', max_length=10, null=True)),
                ('indicator', models.CharField(blank=True, db_column='INDICATOR', max_length=30, null=True)),
                ('regist_dt', models.DateTimeField(blank=True, db_column='REGIST_DT', null=True)),
            ],
            options={
                'db_table': 't_detail_indicator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TIndicator',
            fields=[
                ('indicator', models.CharField(db_column='INDICATOR', max_length=50, primary_key=True, serialize=False)),
                ('parent_indicator', models.CharField(db_column='PARENT_INDICATOR', max_length=50)),
                ('indicator_nm', models.CharField(blank=True, db_column='INDICATOR_NM', max_length=100, null=True)),
                ('indicator_val', models.CharField(blank=True, db_column='INDICATOR_VAL', max_length=30, null=True)),
                ('indicator_etc', models.CharField(blank=True, db_column='INDICATOR_ETC', max_length=30, null=True)),
                ('regist_dt', models.DateTimeField(blank=True, db_column='REGIST_DT', null=True)),
            ],
            options={
                'db_table': 't_indicator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUnityIndicator',
            fields=[
                ('unity_indicator_seq', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='CODE', max_length=50, null=True)),
                ('gubun', models.CharField(blank=True, db_column='GUBUN', max_length=50, null=True)),
                ('year', models.CharField(blank=True, db_column='YEAR', max_length=10, null=True)),
                ('unity_index', models.CharField(blank=True, db_column='UNITY_INDEX', max_length=10, null=True)),
                ('regist_dt', models.DateTimeField(blank=True, db_column='REGIST_DT', null=True)),
            ],
            options={
                'db_table': 't_unity_indicator',
                'managed': False,
            },
        ),
    ]
