# Generated by Django 3.2.7 on 2021-10-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_seq', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dept_nm', models.CharField(max_length=255)),
                ('upper_dept_seq', models.CharField(max_length=255)),
                ('all_dept_seq', models.CharField(max_length=255)),
                ('sort', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_dept',
            },
        ),
    ]
