# Generated by Django 3.2.3 on 2021-10-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('indicator', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parent_indicator', models.CharField(max_length=50)),
                ('indicator_nm', models.CharField(max_length=100)),
                ('indicator_val', models.CharField(max_length=30)),
                ('indicator_etc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_indicator',
            },
        ),
    ]
