# Generated by Django 2.2.5 on 2021-10-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_vdetailindex_vunityindex'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vdetailindex',
            table='v_detail_indicator_final',
        ),
        migrations.AlterModelTable(
            name='vunityindex',
            table='v_unity_indicator_final',
        ),
    ]
